### ISSUE TITLE
Uploading games and screenshots

### ISSUE THREAD

**Issue by TheExDeus** [enigma-dev/EDC#3]
I would want all the file connected to the game to be on enigma servers, so there wouldn't be any broken links or problems with hosting client side (like we use dropbox for this mostly, but dropbox actually will ban users if you have extensive traffic like this). While ENIGMA and EDC is not that popular I don't think you will have a big problem with bandwidth or space (especially when most of the examples and games are very small). That would also allow creating thumbnails for images and a lot better way to actually open them (now you must right click -> show image to actually see the otherwise extremely tiny screenshot).

**Comment by JoshDreamland** [comment]
I moved the files to cloud hosting years ago, and recently (in the last year) added support for uploading to the cloud directly. So, case closed.
